title: AI/ML/DS Conference Deadlines 4 Africans # 
# email: vukosi.marivate@cs.up.ac.za
description: Countdowns to AI/ML/DS conference deadlines for Africans
author: Mpho Mokoatle, Vukosi Marivate, Avashlin Moodley

domain: "https://ds4si.github.io/deadlines/"
baseurl: "https://ds4si.github.io/deadlines/"

twitter_username: ds4si
twitter_hashtag: africanmachinelearning
github_username: ds4si
github_repo: deadlines

markdown: kramdown
ga_id: 

include: ['_pages']
