title: AI Conference Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to AI/ML/DS conference deadlines for Africans
author: Mpho Mokoatle, Vukosi Marivate, Avashlin Moodley

domain: "vukosim.github.cio/ai-ds-africa-deadlines"
baseurl: ""

twitter_username: vukosi
twitter_hashtag: africanmachinelearning
github_username: vukosim
github_repo: ai-ds-africa-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
