title: AI/ML/DS Conference Deadlines 4 Africans # 
# email: vukosi.marivate@cs.up.ac.za
description: Countdowns to AI/ML/DS conference deadlines for Africans
author: Mpho Mokoatle, Vukosi Marivate, Avashlin Moodley

domain: "vukosim.github.cio/ai-ds-africa-deadlines"
baseurl: "vukosim.github.cio/ai-ds-africa-deadlines"

twitter_username: vukosi
twitter_hashtag: africanmachinelearning
github_username: vukosim
github_repo: ai-ds-africa-deadlines

markdown: kramdown
ga_id: 

include: ['_pages']
